<table>
<tbody>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4460.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4460.png" alt="NGC4460" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc2859.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc2859.png" alt="NGC2859" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3619.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3619.png" alt="NGC3619" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3945.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3945.png" alt="NGC3945" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=187.18983333&amp;dec=44.86422222&amp;zoom=12">NGC4460</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=141.07720833&amp;dec=34.51350000&amp;zoom=12">NGC2859</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=169.83983333&amp;dec=57.75783333&amp;zoom=12">NGC3619</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=178.30720833&amp;dec=60.67555556&amp;zoom=12">NGC3945</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5866.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5866.png" alt="NGC5866" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4220.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4220.png" alt="NGC4220" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5689.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5689.png" alt="NGC5689" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5389.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5389.png" alt="NGC5389" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=226.62291667&amp;dec=55.76322222&amp;zoom=12">NGC5866</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=184.04879167&amp;dec=47.88325000&amp;zoom=12">NGC4220</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=218.87370833&amp;dec=48.74163889&amp;zoom=12">NGC5689</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=209.02637500&amp;dec=59.74205556&amp;zoom=12">NGC5389</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc2782.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc2782.png" alt="NGC2782" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4736.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4736.png" alt="NGC4736 = M94" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5448.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5448.png" alt="NGC5448" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3898.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3898.png" alt="NGC3898" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=138.52129167&amp;dec=40.11369444&amp;zoom=12">NGC2782</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=192.72108333&amp;dec=41.12044444&amp;zoom=12">NGC4736 = M94</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=210.70845833&amp;dec=49.17269444&amp;zoom=12">NGC5448</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=177.31404167&amp;dec=56.08436111&amp;zoom=12">NGC3898</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5965.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5965.png" alt="NGC5965" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5963.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5963.png" alt="NGC5963" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5908.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5908.png" alt="NGC5908" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5905.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5905.png" alt="NGC5905" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=233.51025000&amp;dec=56.68561111&amp;zoom=12">NGC5965</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=233.36608333&amp;dec=56.55969444&amp;zoom=12">NGC5963</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=229.18008333&amp;dec=55.40925000&amp;zoom=12">NGC5908</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=228.84716667&amp;dec=55.51736111&amp;zoom=12">NGC5905</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc2424.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc2424.png" alt="NGC2424" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5005.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5005.png" alt="NGC5005" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5985.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5985.png" alt="NGC5985" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4157.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4157.png" alt="NGC4157" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=115.16370833&amp;dec=39.23330556&amp;zoom=12">NGC2424</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=197.73429167&amp;dec=37.05919444&amp;zoom=12">NGC5005</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=234.90454167&amp;dec=59.33194444&amp;zoom=12">NGC5985</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=182.76820833&amp;dec=50.48466667&amp;zoom=12">NGC4157</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4051.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4051.png" alt="NGC4051" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4013.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4013.png" alt="NGC4013" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3972.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3972.png" alt="NGC3972" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3675.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3675.png" alt="NGC3675" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=180.79004167&amp;dec=44.53133333&amp;zoom=12">NGC4051</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=179.63075000&amp;dec=43.94658333&amp;zoom=12">NGC4013</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=178.93787500&amp;dec=55.32075000&amp;zoom=12">NGC3972</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=171.53575000&amp;dec=43.58591667&amp;zoom=12">NGC3675</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5194.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5194.png" alt="NGC5194 = M51 = Whirlpool Galaxy" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5987.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5987.png" alt="NGC5987" /></a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=202.46962500&amp;dec=47.19516667&amp;zoom=12">NGC5194 = M51 = Whirlpool Galaxy</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=234.98904167&amp;dec=58.07952778&amp;zoom=12">NGC5987</a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
</tbody>
</table>
