<table>
<tbody>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3642.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3642.png" alt="NGC3642" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4258.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4258.png" alt="NGC4258 = M106" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3003.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3003.png" alt="NGC3003" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3992.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3992.png" alt="NGC3992 = M109" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=170.57454167&amp;dec=59.07452778&amp;zoom=12">NGC3642</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=184.73958333&amp;dec=47.30397222&amp;zoom=12">NGC4258 = M106</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=147.15020833&amp;dec=33.42150000&amp;zoom=12">NGC3003</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=179.39991667&amp;dec=53.37452778&amp;zoom=12">NGC3992 = M109</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3953.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3953.png" alt="NGC3953" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5371.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5371.png" alt="NGC5371" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5290.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5290.png" alt="NGC5290" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5023.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5023.png" alt="NGC5023" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=178.45383333&amp;dec=52.32677778&amp;zoom=12">NGC3953</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=208.91641667&amp;dec=40.46175000&amp;zoom=12">NGC5371</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=206.32991667&amp;dec=41.71258333&amp;zoom=12">NGC5290</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=198.05250000&amp;dec=44.04122222&amp;zoom=12">NGC5023</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5033.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5033.png" alt="NGC5033" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc2541.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc2541.png" alt="NGC2541" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5301.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5301.png" alt="NGC5301" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5529.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5529.png" alt="NGC5529" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=198.36445833&amp;dec=36.59394444&amp;zoom=12">NGC5033</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=123.66716667&amp;dec=49.06172222&amp;zoom=12">NGC2541</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=206.60279167&amp;dec=46.10705556&amp;zoom=12">NGC5301</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=213.89195833&amp;dec=36.22658333&amp;zoom=12">NGC5529</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5585.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5585.png" alt="NGC5585" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5676.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5676.png" alt="NGC5676" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc5906.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc5906.png" alt="NGC5906" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4244.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4244.png" alt="NGC4244" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=214.95083333&amp;dec=56.72905556&amp;zoom=12">NGC5585</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=218.19520833&amp;dec=49.45788889&amp;zoom=12">NGC5676</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=228.97404167&amp;dec=56.32877778&amp;zoom=12">NGC5906</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=184.37358333&amp;dec=37.80711111&amp;zoom=12">NGC4244</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4183.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4183.png" alt="NGC4183" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4096.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4096.png" alt="NGC4096" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc6207.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc6207.png" alt="NGC6207" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4088.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4088.png" alt="NGC4088" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=183.32033333&amp;dec=43.69858333&amp;zoom=12">NGC4183</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=181.50470833&amp;dec=47.47844444&amp;zoom=12">NGC4096</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=250.76562500&amp;dec=36.83241667&amp;zoom=12">NGC6207</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=181.39245833&amp;dec=50.53902778&amp;zoom=12">NGC4088</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3938.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3938.png" alt="NGC3938" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3917.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3917.png" alt="NGC3917" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3726.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3726.png" alt="NGC3726" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3631.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3631.png" alt="NGC3631" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=178.20604167&amp;dec=44.12072222&amp;zoom=12">NGC3938</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=177.68929167&amp;dec=51.82466667&amp;zoom=12">NGC3917</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=173.33800000&amp;dec=47.02919444&amp;zoom=12">NGC3726</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=170.26195833&amp;dec=53.16955556&amp;zoom=12">NGC3631</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3556.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3556.png" alt="NGC3556 = M108" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3319.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3319.png" alt="NGC3319" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3294.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3294.png" alt="NGC3294" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc3184.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc3184.png" alt="NGC3184" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=167.87904167&amp;dec=55.67411111&amp;zoom=12">NGC3556 = M108</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=159.78941667&amp;dec=41.68666667&amp;zoom=12">NGC3319</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=159.06770833&amp;dec=37.32469444&amp;zoom=12">NGC3294</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=154.57025000&amp;dec=41.42405556&amp;zoom=12">NGC3184</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc2770.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc2770.png" alt="NGC2770" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc6255.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc6255.png" alt="NGC6255" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4010.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4010.png" alt="NGC4010" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4490.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4490.png" alt="NGC4490" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=137.39045833&amp;dec=33.12352778&amp;zoom=12">NGC2770</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=253.69979167&amp;dec=36.50111111&amp;zoom=12">NGC6255</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=179.65787500&amp;dec=47.26150000&amp;zoom=12">NGC4010</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=187.65100000&amp;dec=41.64388889&amp;zoom=12">NGC4490</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4145.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4145.png" alt="NGC4145" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/ngc4242.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr6/gallery/png/thumb-ngc4242.png" alt="NGC4242" /></a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=182.50633333&amp;dec=39.88386111&amp;zoom=12">NGC4145</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&amp;ra=184.37575000&amp;dec=45.61930556&amp;zoom=12">NGC4242</a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
</tbody>
</table>
