<table>
<tbody>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_12891.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_12891.png" alt="UGC 12891"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_00212.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_00212.png" alt="UGC 00212"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_00224.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_00224.png" alt="UGC 00224"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_251.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_251.png" alt="ARP 251"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=0.08167000&dec=22.99194000&zoom=12">UGC 12891</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=5.59596000&dec=-1.30339000&zoom=12">UGC 00212</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=5.90708000&dec=-0.50639000&zoom=12">UGC 00224</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=13.45158000&dec=-13.85692000&zoom=12">ARP 251</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_1623b.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_1623b.png" alt="IC 1623B"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_00827.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_00827.png" alt="UGC 00827"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_088.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_088.png" alt="ARP 088"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/mrk_0983.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-mrk_0983.png" alt="MRK 0983"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=16.94817000&dec=-17.50697000&zoom=12">IC 1623B</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=19.36958000&dec=14.70333000&zoom=12">UGC 00827</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=19.77167000&dec=12.47333000&zoom=12">ARP 088</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=19.84406000&dec=12.40362000&zoom=12">MRK 0983</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_054.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_054.png" alt="ARP 054"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_2339.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_2339.png" alt="IC 2339"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ngc_3068.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ngc_3068.png" alt="NGC 3068"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_05764.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_05764.png" alt="UGC 05764"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=36.01100000&dec=-4.69297000&zoom=12">ARP 054</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.89255000&dec=21.34764000&zoom=12">IC 2339</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=149.66292000&dec=28.87417000&zoom=12">NGC 3068</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=159.18057000&dec=31.54674000&zoom=12">UGC 05764</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_06073.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_06073.png" alt="UGC 06073"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_132.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_132.png" alt="ARP 132"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_0701.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_0701.png" alt="IC 0701"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_06678.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_06678.png" alt="UGC 06678"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=164.94167000&dec=17.65286000&zoom=12">UGC 06073</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=169.85458000&dec=-3.09222000&zoom=12">ARP 132</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=172.75284000&dec=20.46895000&zoom=12">IC 0701</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=175.75788000&dec=26.25842000&zoom=12">UGC 06678</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_07085a.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_07085a.png" alt="UGC 07085A"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_3481a.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_3481a.png" alt="IC 3481A"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_3483.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_3483.png" alt="IC 3483"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_0803.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_0803.png" alt="IC 0803"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=181.43958000&dec=31.06889000&zoom=12">UGC 07085A</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=188.23646000&dec=11.38996000&zoom=12">IC 3481A</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=188.29191000&dec=11.34734000&zoom=12">IC 3483</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=189.90423000&dec=16.58803000&zoom=12">IC 0803</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_139.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_139.png" alt="ARP 139"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_057.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_057.png" alt="ARP 057"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_08548.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_08548.png" alt="UGC 08548"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_08613.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_08613.png" alt="UGC 08613"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=196.86542000&dec=26.72472000&zoom=12">ARP 139</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=199.19875000&dec=14.42444000&zoom=12">ARP 057</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=203.56229000&dec=31.42500000&zoom=12">UGC 08548</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=204.34959000&dec=6.43667000&zoom=12">UGC 08613</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ngc_5614_group.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ngc_5614_group.png" alt="NGC 5614 Group"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ic_4462.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ic_4462.png" alt="IC 4462"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_09425.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_09425.png" alt="UGC 09425"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_09503.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_09503.png" alt="UGC 09503"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=216.02850000&dec=34.87310000&zoom=12">NGC 5614 Group</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=218.75793000&dec=26.54392000&zoom=12">IC 4462</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=219.46196000&dec=30.48122000&zoom=12">UGC 09425</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=221.35976000&dec=19.46572000&zoom=12">UGC 09503</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_047.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_047.png" alt="ARP 047"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ugc_09561.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ugc_09561.png" alt="UGC 09561"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ngc_5829_group.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ngc_5829_group.png" alt="NGC 5829 Group"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ngc_5996_group.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ngc_5996_group.png" alt="NGC 5996 Group"></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=221.80667000&dec=18.85861000&zoom=12">ARP 047</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=222.86642000&dec=9.32194000&zoom=12">UGC 09561</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=225.66500000&dec=23.34340000&zoom=12">NGC 5829 Group</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.73290000&dec=17.88110000&zoom=12">NGC 5996 Group</a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/arp_218.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-arp_218.png" alt="ARP 218"></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/ngc_3746_group.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr7/gallery/png/thumb-ngc_3746_group.png" alt="NGC 3746 Group"></a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.39750000&dec=18.60722000&zoom=12">ARP 218</a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=174.45880000&dec=21.99800000&zoom=12">NGC 3746 Group</a></td>
<td style="width:20%;word-wrap:break-word;"></td>
<td style="width:20%;word-wrap:break-word;"></td>
</tr>
</tbody>
</table>
