<table>
<tbody>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/CGCG49-52.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-CGCG49-52.png" alt="CGCG49-52" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1063.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1063.png" alt="IC1063" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1102.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1102.png" alt="IC1102" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1105.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1105.png" alt="IC1105" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1149.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1149.png" alt="IC1149" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.3367&dec=2.51376&zoom=14">CGCG49-52</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=223.0459&dec=4.68205&zoom=14">IC1063</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.7706&dec=4.29387&zoom=14">IC1102</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.3079&dec=4.28754&zoom=14">IC1105</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=239.5333&dec=12.07028&zoom=14">IC1149</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1169.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1169.png" alt="IC1169" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1196.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1196.png" alt="IC1196" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1197.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1197.png" alt="IC1197" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1199.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1199.png" alt="IC1199" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1206.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1206.png" alt="IC1206" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.0559&dec=13.74400&zoom=14">IC1169</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.9932&dec=10.77964&zoom=14">IC1196</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=242.0720&dec=7.53850&zoom=14">IC1197</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=242.6431&dec=10.04039&zoom=14">IC1199</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=243.8045&dec=11.29742&zoom=14">IC1206</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1361.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1361.png" alt="IC1361" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1365.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1365.png" alt="IC1365" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1368.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1368.png" alt="IC1368" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1401.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1401.png" alt="IC1401" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1411.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1411.png" alt="IC1411" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=317.8714&dec=5.05432&zoom=14">IC1361</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=318.4833&dec=2.56556&zoom=14">IC1365</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=318.5525&dec=2.17800&zoom=14">IC1368</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=326.7479&dec=1.71275&zoom=14">IC1401</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=329.0025&dec=-1.51705&zoom=14">IC1411</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1455.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1455.png" alt="IC1455" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC1507.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC1507.png" alt="IC1507" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC2239.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC2239.png" alt="IC2239" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC2435.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC2435.png" alt="IC2435" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC2486.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC2486.png" alt="IC2486" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=343.4419&dec=1.37199&zoom=14">IC1455</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.3882&dec=1.68875&zoom=14">IC1507</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=123.5283&dec=23.86633&zoom=14">IC2239</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=136.7074&dec=26.27535&zoom=14">IC2435</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=142.5724&dec=26.64128&zoom=14">IC2486</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC3391.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC3391.png" alt="IC3391" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC3473.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC3473.png" alt="IC3473" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC3615.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC3615.png" alt="IC3615" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC494.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC494.png" alt="IC494" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC5090.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC5090.png" alt="IC5090" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=187.1137&dec=18.41531&zoom=14">IC3391</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=188.0797&dec=18.24413&zoom=14">IC3473</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=189.7567&dec=18.20067&zoom=14">IC3615</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=121.6005&dec=1.03606&zoom=14">IC494</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=317.8770&dec=-2.03256&zoom=14">IC5090</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC523.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC523.png" alt="IC523" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC5287.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC5287.png" alt="IC5287" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC536.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC536.png" alt="IC536" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC560.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC560.png" alt="IC560" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC588.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC588.png" alt="IC588" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=133.2972&dec=9.14817&zoom=14">IC523</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=347.3345&dec=0.75648&zoom=14">IC5287</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=141.1671&dec=25.11017&zoom=14">IC536</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=146.4726&dec=-0.26828&zoom=14">IC560</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=150.5292&dec=3.05761&zoom=14">IC588</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC851.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC851.png" alt="IC851" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/IC962-MCG2-36-2.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-IC962-MCG2-36-2.png" alt="IC962-MCG2-36-2" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG-1-57-21.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG-1-57-21.png" alt="MCG-1-57-21" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG-1-7-13.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG-1-7-13.png" alt="MCG-1-7-13" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG0-56-13.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG0-56-13.png" alt="MCG0-56-13" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=197.1431&dec=21.04978&zoom=14">IC851</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=209.3064&dec=12.00942&zoom=14">IC962-MCG2-36-2</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=340.0630&dec=-2.42406&zoom=14">MCG-1-57-21</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=36.8232&dec=-3.89950&zoom=14">MCG-1-7-13</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=332.9705&dec=0.10872&zoom=14">MCG0-56-13</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG0-57-2.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG0-57-2.png" alt="MCG0-57-2" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG0-60-58.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG0-60-58.png" alt="MCG0-60-58" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG1-54-3.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG1-54-3.png" alt="MCG1-54-3" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG2-35-24.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG2-35-24.png" alt="MCG2-35-24" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG3-32-46.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG3-32-46.png" alt="MCG3-32-46" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=337.2151&dec=1.89839&zoom=14">MCG0-57-2</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=358.5420&dec=0.38286&zoom=14">MCG0-60-58</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=318.1987&dec=8.78233&zoom=14">MCG1-54-3</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=208.5193&dec=13.59371&zoom=14">MCG2-35-24</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=187.0360&dec=20.17947&zoom=14">MCG3-32-46</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG3-41-90.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG3-41-90.png" alt="MCG3-41-90" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG5-20-11.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG5-20-11.png" alt="MCG5-20-11" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/MCG5-25-9.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-MCG5-25-9.png" alt="MCG5-25-9" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2512.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2512.png" alt="NGC2512" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2535.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2535.png" alt="NGC2535" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.3494&dec=14.64772&zoom=14">MCG3-41-90</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.8731&dec=27.13492&zoom=14">MCG5-20-11</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=156.4488&dec=26.57069&zoom=14">MCG5-25-9</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=120.7827&dec=23.39186&zoom=14">NGC2512</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=122.8062&dec=25.20681&zoom=14">NGC2535</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2538.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2538.png" alt="NGC2538" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2572.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2572.png" alt="NGC2572" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2592.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2592.png" alt="NGC2592" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2598.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2598.png" alt="NGC2598" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2607.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2607.png" alt="NGC2607" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=122.8462&dec=3.63308&zoom=14">NGC2538</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.3526&dec=19.14778&zoom=14">NGC2572</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=126.7836&dec=25.97033&zoom=14">NGC2592</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=127.5105&dec=21.48864&zoom=14">NGC2598</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=128.4860&dec=26.97254&zoom=14">NGC2607</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2620.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2620.png" alt="NGC2620" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2622.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2622.png" alt="NGC2622" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2623.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2623.png" alt="NGC2623" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2628.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2628.png" alt="NGC2628" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2723.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2723.png" alt="NGC2723" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=129.3677&dec=24.94694&zoom=14">NGC2620</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=129.5456&dec=24.89528&zoom=14">NGC2622</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=129.6003&dec=25.75462&zoom=14">NGC2623</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=130.0946&dec=23.53967&zoom=14">NGC2628</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.0599&dec=3.17772&zoom=14">NGC2723</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2735.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2735.png" alt="NGC2735" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2750.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2750.png" alt="NGC2750" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2824.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2824.png" alt="NGC2824" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC2862.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC2862.png" alt="NGC2862" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3209.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3209.png" alt="NGC3209" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.6610&dec=25.93453&zoom=14">NGC2735</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=136.4496&dec=25.43742&zoom=14">NGC2750</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=139.7593&dec=26.26998&zoom=14">NGC2824</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=141.2296&dec=26.77467&zoom=14">NGC2862</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=155.1600&dec=25.50500&zoom=14">NGC3209</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3720.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3720.png" alt="NGC3720" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3821.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3821.png" alt="NGC3821" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3840.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3840.png" alt="NGC3840" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3886.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3886.png" alt="NGC3886" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC3919.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC3919.png" alt="NGC3919" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=173.0900&dec=0.80406&zoom=14">NGC3720</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=175.5379&dec=20.31572&zoom=14">NGC3821</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=175.9959&dec=20.07704&zoom=14">NGC3840</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=176.7733&dec=19.83725&zoom=14">NGC3886</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=177.6730&dec=20.01514&zoom=14">NGC3919</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4045.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4045.png" alt="NGC4045" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4061-NGC4065.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4061-NGC4065.png" alt="NGC4061-NGC4065" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4075.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4075.png" alt="NGC4075" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4116.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4116.png" alt="NGC4116" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4155.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4155.png" alt="NGC4155" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=180.6760&dec=1.97680&zoom=14">NGC4045</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=181.0157&dec=20.23362&zoom=14">NGC4061-NGC4065</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=181.1575&dec=2.07261&zoom=14">NGC4075</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=181.9048&dec=2.69050&zoom=14">NGC4116</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=182.6903&dec=19.04081&zoom=14">NGC4155</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4158.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4158.png" alt="NGC4158" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4204.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4204.png" alt="NGC4204" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4293.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4293.png" alt="NGC4293" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4336.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4336.png" alt="NGC4336" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4344.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4344.png" alt="NGC4344" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=182.7923&dec=20.17572&zoom=14">NGC4158</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=183.8098&dec=20.65900&zoom=14">NGC4204</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=185.3037&dec=18.38239&zoom=14">NGC4293</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=185.8742&dec=19.42697&zoom=14">NGC4336</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=185.9061&dec=17.54086&zoom=14">NGC4344</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4394.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4394.png" alt="NGC4394" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4493.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4493.png" alt="NGC4493" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4539.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4539.png" alt="NGC4539" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4561.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4561.png" alt="NGC4561" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC4635.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC4635.png" alt="NGC4635" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=186.4818&dec=18.21392&zoom=14">NGC4394</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=187.7904&dec=0.61000&zoom=14">NGC4493</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=188.6448&dec=18.20261&zoom=14">NGC4539</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=189.0339&dec=19.32261&zoom=14">NGC4561</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=190.6635&dec=19.94525&zoom=14">NGC4635</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5202.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5202.png" alt="NGC5202" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5505.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5505.png" alt="NGC5505" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5550.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5550.png" alt="NGC5550" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5587.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5587.png" alt="NGC5587" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5613.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5613.png" alt="NGC5613" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=203.0021&dec=-1.69878&zoom=14">NGC5202</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=213.1333&dec=13.30447&zoom=14">NGC5505</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=214.6165&dec=12.88303&zoom=14">NGC5550</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=215.5447&dec=13.91797&zoom=14">NGC5587</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=216.0249&dec=34.89206&zoom=14">NGC5613</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5614.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5614.png" alt="NGC5614" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5646.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5646.png" alt="NGC5646" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5758.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5758.png" alt="NGC5758" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5839.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5839.png" alt="NGC5839" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5845.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5845.png" alt="NGC5845" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=216.0315&dec=34.85900&zoom=14">NGC5614</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=217.3915&dec=35.46182&zoom=14">NGC5646</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=221.7587&dec=13.66831&zoom=14">NGC5758</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=226.3645&dec=1.63472&zoom=14">NGC5839</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=226.5033&dec=1.63381&zoom=14">NGC5845</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5846.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5846.png" alt="NGC5846" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5848.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5848.png" alt="NGC5848" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5864.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5864.png" alt="NGC5864" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5868.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5868.png" alt="NGC5868" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5887.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5887.png" alt="NGC5887" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=226.6220&dec=1.60562&zoom=14">NGC5846</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=226.6460&dec=2.00482&zoom=14">NGC5848</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.3898&dec=3.05275&zoom=14">NGC5864</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.4549&dec=0.52979&zoom=14">NGC5868</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.6831&dec=1.15415&zoom=14">NGC5887</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5936.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5936.png" alt="NGC5936" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5957.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5957.png" alt="NGC5957" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5984.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5984.png" alt="NGC5984" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC5990.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC5990.png" alt="NGC5990" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6007.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6007.png" alt="NGC6007" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=232.5035&dec=12.98931&zoom=14">NGC5936</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=233.8468&dec=12.04730&zoom=14">NGC5957</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.7216&dec=14.23142&zoom=14">NGC5984</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.5682&dec=2.41547&zoom=14">NGC5990</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.3465&dec=11.95914&zoom=14">NGC6007</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6012.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6012.png" alt="NGC6012" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6014.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6014.png" alt="NGC6014" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6017.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6017.png" alt="NGC6017" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6036.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6036.png" alt="NGC6036" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6063.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6063.png" alt="NGC6063" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.5581&dec=14.60125&zoom=14">NGC6012</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.9892&dec=5.93189&zoom=14">NGC6014</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=239.3145&dec=5.99836&zoom=14">NGC6017</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.1281&dec=3.86847&zoom=14">NGC6036</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.8042&dec=7.97900&zoom=14">NGC6063</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6081.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6081.png" alt="NGC6081" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6092.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6092.png" alt="NGC6092" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6106.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6106.png" alt="NGC6106" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6132.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6132.png" alt="NGC6132" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6364.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6364.png" alt="NGC6364" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=243.2370&dec=9.86717&zoom=14">NGC6081</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=243.1955&dec=27.98740&zoom=14">NGC6092</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=244.6967&dec=7.41097&zoom=14">NGC6106</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=245.9117&dec=11.78633&zoom=14">NGC6132</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=261.1139&dec=29.39017&zoom=14">NGC6364</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC6372.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC6372.png" alt="NGC6372" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7040.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7040.png" alt="NGC7040" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7047.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7047.png" alt="NGC7047" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7069.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7069.png" alt="NGC7069" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7077.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7077.png" alt="NGC7077" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=261.8827&dec=26.47511&zoom=14">NGC6372</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=318.3188&dec=8.86497&zoom=14">NGC7040</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=319.1152&dec=-0.82650&zoom=14">NGC7047</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=322.0245&dec=-1.64686&zoom=14">NGC7069</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=322.4984&dec=2.41417&zoom=14">NGC7077</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7102.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7102.png" alt="NGC7102" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7164.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7164.png" alt="NGC7164" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7181.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7181.png" alt="NGC7181" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7182.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7182.png" alt="NGC7182" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7189.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7189.png" alt="NGC7189" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=324.9354&dec=6.28630&zoom=14">NGC7102</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=329.0985&dec=1.36394&zoom=14">NGC7164</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=330.4312&dec=-1.96055&zoom=14">NGC7181</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=330.4653&dec=-2.19658&zoom=14">NGC7182</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=330.8167&dec=0.57111&zoom=14">NGC7189</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7198.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7198.png" alt="NGC7198" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7215.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7215.png" alt="NGC7215" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7222.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7222.png" alt="NGC7222" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7364.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7364.png" alt="NGC7364" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7391.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7391.png" alt="NGC7391" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=331.3093&dec=-0.64829&zoom=14">NGC7198</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=332.1437&dec=0.51169&zoom=14">NGC7215</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=332.7157&dec=2.10580&zoom=14">NGC7222</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=341.1016&dec=-0.16208&zoom=14">NGC7364</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=342.6505&dec=-1.54483&zoom=14">NGC7391</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7396.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7396.png" alt="NGC7396" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7398.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7398.png" alt="NGC7398" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7428.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7428.png" alt="NGC7428" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7458.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7458.png" alt="NGC7458" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7589.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7589.png" alt="NGC7589" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=343.0942&dec=1.09253&zoom=14">NGC7396</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=343.2053&dec=1.20111&zoom=14">NGC7398</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=344.3314&dec=-1.04900&zoom=14">NGC7428</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=345.3693&dec=1.75339&zoom=14">NGC7458</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=349.5653&dec=0.26116&zoom=14">NGC7589</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7603.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7603.png" alt="NGC7603" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7629.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7629.png" alt="NGC7629" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7667.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7667.png" alt="NGC7667" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7684.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7684.png" alt="NGC7684" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7693.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7693.png" alt="NGC7693" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=349.7359&dec=0.24395&zoom=14">NGC7603</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=350.3307&dec=1.40312&zoom=14">NGC7629</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=351.0962&dec=-0.10806&zoom=14">NGC7667</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=352.6335&dec=0.08103&zoom=14">NGC7684</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.2938&dec=-1.29185&zoom=14">NGC7693</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7716.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7716.png" alt="NGC7716" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7738.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7738.png" alt="NGC7738" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7739.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7739.png" alt="NGC7739" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7746.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7746.png" alt="NGC7746" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/NGC7787.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-NGC7787.png" alt="NGC7787" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=354.1311&dec=0.29731&zoom=14">NGC7716</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.0085&dec=0.51672&zoom=14">NGC7738</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.1253&dec=0.32044&zoom=14">NGC7739</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.3333&dec=-1.68489&zoom=14">NGC7746</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=359.0326&dec=0.54950&zoom=14">NGC7787</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/PGC70104.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-PGC70104.png" alt="PGC70104" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10000.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10000.png" alt="UGC10000" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10005.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10005.png" alt="UGC10005" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10009.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10009.png" alt="UGC10009" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10014.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10014.png" alt="UGC10014" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=344.3817&dec=-2.49861&zoom=14">PGC70104</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.2061&dec=3.95633&zoom=14">UGC10000</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.3099&dec=0.77217&zoom=14">UGC10005</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.4062&dec=4.18250&zoom=14">UGC10009</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.4340&dec=12.50981&zoom=14">UGC10014</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10025.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10025.png" alt="UGC10025" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10026.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10026.png" alt="UGC10026" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10027.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10027.png" alt="UGC10027" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10029.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10029.png" alt="UGC10029" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10041.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10041.png" alt="UGC10041" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.6018&dec=2.84403&zoom=14">UGC10025</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.5737&dec=10.75853&zoom=14">UGC10026</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.6065&dec=4.42764&zoom=14">UGC10027</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=236.7264&dec=5.89122&zoom=14">UGC10029</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=237.2558&dec=5.18861&zoom=14">UGC10041</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10068.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10068.png" alt="UGC10068" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10077.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10077.png" alt="UGC10077" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10082.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10082.png" alt="UGC10082" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10130.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10130.png" alt="UGC10130" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10131.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10131.png" alt="UGC10131" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.0153&dec=12.89872&zoom=14">UGC10068</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.2751&dec=13.23481&zoom=14">UGC10077</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=238.5838&dec=12.12833&zoom=14">UGC10082</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=240.3333&dec=8.83589&zoom=14">UGC10130</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=240.3095&dec=14.07875&zoom=14">UGC10131</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10137.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10137.png" alt="UGC10137" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10158.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10158.png" alt="UGC10158" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10172.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10172.png" alt="UGC10172" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10184.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10184.png" alt="UGC10184" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10203.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10203.png" alt="UGC10203" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=240.4572&dec=8.14819&zoom=14">UGC10137</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=240.9807&dec=11.72872&zoom=14">UGC10158</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.1976&dec=14.28725&zoom=14">UGC10172</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.4118&dec=3.07274&zoom=14">UGC10184</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.7233&dec=3.79350&zoom=14">UGC10203</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10213.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10213.png" alt="UGC10213" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10216.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10216.png" alt="UGC10216" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10225.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10225.png" alt="UGC10225" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10238.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10238.png" alt="UGC10238" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10249.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10249.png" alt="UGC10249" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.8546&dec=10.42578&zoom=14">UGC10213</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=241.9167&dec=13.71936&zoom=14">UGC10216</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=242.3365&dec=8.76325&zoom=14">UGC10225</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=242.6106&dec=12.30564&zoom=14">UGC10238</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=242.8208&dec=13.86621&zoom=14">UGC10249</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10327.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10327.png" alt="UGC10327" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10337.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10337.png" alt="UGC10337" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10373.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10373.png" alt="UGC10373" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10375.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10375.png" alt="UGC10375" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10384.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10384.png" alt="UGC10384" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=244.6250&dec=22.16314&zoom=14">UGC10327</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=244.8692&dec=7.27875&zoom=14">UGC10337</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=246.1764&dec=7.18256&zoom=14">UGC10373</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=246.2085&dec=9.60703&zoom=14">UGC10375</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=246.6945&dec=11.58025&zoom=14">UGC10384</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10414.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10414.png" alt="UGC10414" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10416.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10416.png" alt="UGC10416" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10435.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10435.png" alt="UGC10435" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10463.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10463.png" alt="UGC10463" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10545.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10545.png" alt="UGC10545" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=247.4470&dec=8.64422&zoom=14">UGC10414</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=247.5848&dec=8.62883&zoom=14">UGC10416</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=247.8399&dec=22.69712&zoom=14">UGC10435</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=249.0815&dec=10.36539&zoom=14">UGC10463</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=251.7207&dec=34.41003&zoom=14">UGC10545</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10808.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10808.png" alt="UGC10808" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10842.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10842.png" alt="UGC10842" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10866.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10866.png" alt="UGC10866" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10879.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10879.png" alt="UGC10879" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10894.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10894.png" alt="UGC10894" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=259.8816&dec=28.33161&zoom=14">UGC10808</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=261.2173&dec=28.07828&zoom=14">UGC10842</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=262.1556&dec=26.56111&zoom=14">UGC10866</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=262.4833&dec=24.88383&zoom=14">UGC10879</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=263.2659&dec=27.57475&zoom=14">UGC10894</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC10909.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC10909.png" alt="UGC10909" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11695.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11695.png" alt="UGC11695" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11714.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11714.png" alt="UGC11714" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11723.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11723.png" alt="UGC11723" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11724.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11724.png" alt="UGC11724" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=263.6581&dec=25.56850&zoom=14">UGC10909</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=318.0438&dec=-1.47525&zoom=14">UGC11695</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=319.4429&dec=2.36883&zoom=14">UGC11714</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=320.0728&dec=-1.68433&zoom=14">UGC11723</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=320.1593&dec=1.04719&zoom=14">UGC11724</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11725.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11725.png" alt="UGC11725" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11733.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11733.png" alt="UGC11733" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11740.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11740.png" alt="UGC11740" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11765.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11765.png" alt="UGC11765" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11773.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11773.png" alt="UGC11773" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=320.2573&dec=9.17750&zoom=14">UGC11725</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=320.5063&dec=7.14531&zoom=14">UGC11733</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=321.5598&dec=9.79801&zoom=14">UGC11740</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=323.3882&dec=8.77249&zoom=14">UGC11765</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=324.0295&dec=9.66047&zoom=14">UGC11773</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11782.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11782.png" alt="UGC11782" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11789.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11789.png" alt="UGC11789" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11790.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11790.png" alt="UGC11790" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11792.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11792.png" alt="UGC11792" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11814.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11814.png" alt="UGC11814" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=324.5404&dec=8.96139&zoom=14">UGC11782</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=325.2503&dec=1.33506&zoom=14">UGC11789</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=325.3749&dec=0.89465&zoom=14">UGC11790</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=325.5533&dec=5.61531&zoom=14">UGC11792</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=327.1103&dec=-1.67269&zoom=14">UGC11814</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11816.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11816.png" alt="UGC11816" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11825.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11825.png" alt="UGC11825" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11827.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11827.png" alt="UGC11827" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11853.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11853.png" alt="UGC11853" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11863.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11863.png" alt="UGC11863" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=327.2804&dec=0.44733&zoom=14">UGC11816</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=327.6764&dec=0.91197&zoom=14">UGC11825</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=327.6710&dec=22.85157&zoom=14">UGC11827</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=329.0765&dec=-1.17353&zoom=14">UGC11853</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=329.6040&dec=-0.73956&zoom=14">UGC11863</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC11982.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC11982.png" alt="UGC11982" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12068.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12068.png" alt="UGC12068" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12114.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12114.png" alt="UGC12114" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12151.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12151.png" alt="UGC12151" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12208.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12208.png" alt="UGC12208" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=334.7206&dec=-1.05867&zoom=14">UGC11982</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=338.0302&dec=0.03708&zoom=14">UGC12068</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=339.3461&dec=-1.02541&zoom=14">UGC12114</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=340.3912&dec=0.40100&zoom=14">UGC12151</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=342.5265&dec=-1.04931&zoom=14">UGC12208</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12295.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12295.png" alt="UGC12295" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12336.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12336.png" alt="UGC12336" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12346.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12346.png" alt="UGC12346" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12348.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12348.png" alt="UGC12348" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12452.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12452.png" alt="UGC12452" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=345.0988&dec=1.62653&zoom=14">UGC12295</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=346.0247&dec=1.90758&zoom=14">UGC12336</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=346.3023&dec=0.83441&zoom=14">UGC12346</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=346.3284&dec=0.18944&zoom=14">UGC12348</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=348.7612&dec=1.43556&zoom=14">UGC12452</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12479.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12479.png" alt="UGC12479" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12492.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12492.png" alt="UGC12492" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12503.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12503.png" alt="UGC12503" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12521.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12521.png" alt="UGC12521" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12589.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12589.png" alt="UGC12589" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=349.3570&dec=-1.58617&zoom=14">UGC12479</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=349.7241&dec=-1.06026&zoom=14">UGC12492</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=349.8293&dec=0.94585&zoom=14">UGC12503</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=350.0478&dec=-1.85658&zoom=14">UGC12521</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=351.2566&dec=0.00020&zoom=14">UGC12589</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12635.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12635.png" alt="UGC12635" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12656.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12656.png" alt="UGC12656" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12659.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12659.png" alt="UGC12659" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12661.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12661.png" alt="UGC12661" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12685.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12685.png" alt="UGC12685" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=352.6070&dec=0.15669&zoom=14">UGC12635</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.1350&dec=-1.74081&zoom=14">UGC12656</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.1830&dec=-1.78339&zoom=14">UGC12659</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.3700&dec=-1.98369&zoom=14">UGC12661</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.8074&dec=0.04244&zoom=14">UGC12685</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12690.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12690.png" alt="UGC12690" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12709.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12709.png" alt="UGC12709" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12729.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12729.png" alt="UGC12729" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12739.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12739.png" alt="UGC12739" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12769.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12769.png" alt="UGC12769" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=353.9151&dec=1.19810&zoom=14">UGC12690</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=354.3501&dec=0.39168&zoom=14">UGC12709</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=355.0865&dec=1.24586&zoom=14">UGC12729</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=355.4430&dec=-1.35164&zoom=14">UGC12739</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.3301&dec=-1.27341&zoom=14">UGC12769</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12774.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12774.png" alt="UGC12774" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12810.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12810.png" alt="UGC12810" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC12857.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC12857.png" alt="UGC12857" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC3916.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC3916.png" alt="UGC3916" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC3939.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC3939.png" alt="UGC3939" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=356.5145&dec=-1.89089&zoom=14">UGC12774</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=357.7760&dec=1.05667&zoom=14">UGC12810</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=359.1984&dec=1.35501&zoom=14">UGC12857</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=113.7049&dec=22.57647&zoom=14">UGC3916</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=114.3315&dec=19.97599&zoom=14">UGC3939</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC3960.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC3960.png" alt="UGC3960" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC3995.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC3995.png" alt="UGC3995" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4038.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4038.png" alt="UGC4038" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4135.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4135.png" alt="UGC4135" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4208.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4208.png" alt="UGC4208" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=115.0947&dec=23.27492&zoom=14">UGC3960</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=116.0387&dec=29.24667&zoom=14">UGC3995</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=117.4000&dec=26.90578&zoom=14">UGC4038</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=119.8217&dec=24.45206&zoom=14">UGC4135</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=121.1723&dec=24.87081&zoom=14">UGC4208</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4251.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4251.png" alt="UGC4251" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4253.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4253.png" alt="UGC4253" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4254.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4254.png" alt="UGC4254" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4269.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4269.png" alt="UGC4269" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4341.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4341.png" alt="UGC4341" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=122.3116&dec=0.28276&zoom=14">UGC4251</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=122.3162&dec=-0.36664&zoom=14">UGC4253</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=122.3500&dec=0.60944&zoom=14">UGC4254</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=123.0067&dec=19.36461&zoom=14">UGC4269</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.0413&dec=27.09347&zoom=14">UGC4341</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4346.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4346.png" alt="UGC4346" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4364.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4364.png" alt="UGC4364" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4381.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4381.png" alt="UGC4381" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4418.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4418.png" alt="UGC4418" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4431.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4431.png" alt="UGC4431" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.1700&dec=25.90536&zoom=14">UGC4346</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.6032&dec=25.50901&zoom=14">UGC4364</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=125.8048&dec=-0.86481&zoom=14">UGC4381</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=126.8653&dec=25.72442&zoom=14">UGC4418</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=127.0534&dec=0.02408&zoom=14">UGC4431</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4439.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4439.png" alt="UGC4439" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4450.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4450.png" alt="UGC4450" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4464.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4464.png" alt="UGC4464" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4542.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4542.png" alt="UGC4542" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4575.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4575.png" alt="UGC4575" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=127.3303&dec=2.64506&zoom=14">UGC4439</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=127.8532&dec=27.58006&zoom=14">UGC4450</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=128.2508&dec=26.01403&zoom=14">UGC4464</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=130.7195&dec=25.07042&zoom=14">UGC4542</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=131.4152&dec=23.86881&zoom=14">UGC4575</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4597.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4597.png" alt="UGC4597" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4602.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4602.png" alt="UGC4602" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4624.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4624.png" alt="UGC4624" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4626.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4626.png" alt="UGC4626" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4638B.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4638B.png" alt="UGC4638B" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=131.9175&dec=25.89353&zoom=14">UGC4597</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=131.9825&dec=25.83167&zoom=14">UGC4602</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=132.5983&dec=25.95408&zoom=14">UGC4624</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=132.7548&dec=24.31936&zoom=14">UGC4626</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=132.9087&dec=-2.35417&zoom=14">UGC4638B</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4640.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4640.png" alt="UGC4640" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4651.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4651.png" alt="UGC4651" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4684.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4684.png" alt="UGC4684" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4722.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4722.png" alt="UGC4722" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4745.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4745.png" alt="UGC4745" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=132.9326&dec=-2.13406&zoom=14">UGC4640</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=133.2759&dec=-1.02964&zoom=14">UGC4651</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=134.1695&dec=0.37495&zoom=14">UGC4684</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.0981&dec=25.61129&zoom=14">UGC4722</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.6815&dec=25.09197&zoom=14">UGC4745</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4746.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4746.png" alt="UGC4746" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4748.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4748.png" alt="UGC4748" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4764.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4764.png" alt="UGC4764" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4774.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4774.png" alt="UGC4774" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4802.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4802.png" alt="UGC4802" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.6827&dec=25.42117&zoom=14">UGC4746</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=135.8221&dec=10.01889&zoom=14">UGC4748</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=136.3597&dec=25.55072&zoom=14">UGC4764</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=136.5738&dec=25.58350&zoom=14">UGC4774</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=137.0962&dec=-1.61133&zoom=14">UGC4802</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4804.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4804.png" alt="UGC4804" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4845.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4845.png" alt="UGC4845" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4857.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4857.png" alt="UGC4857" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4902.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4902.png" alt="UGC4902" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4955.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4955.png" alt="UGC4955" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=137.1564&dec=-1.75322&zoom=14">UGC4804</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=138.1078&dec=9.95550&zoom=14">UGC4845</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=138.3058&dec=3.23043&zoom=14">UGC4857</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=139.2720&dec=25.42917&zoom=14">UGC4902</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=140.0808&dec=25.27361&zoom=14">UGC4955</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4957.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4957.png" alt="UGC4957" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4965.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4965.png" alt="UGC4965" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC4994.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC4994.png" alt="UGC4994" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5027.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5027.png" alt="UGC5027" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5094.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5094.png" alt="UGC5094" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=140.0552&dec=8.79300&zoom=14">UGC4957</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=140.2774&dec=24.30783&zoom=14">UGC4965</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=140.8979&dec=24.76164&zoom=14">UGC4994</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=141.5719&dec=3.13486&zoom=14">UGC5027</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=143.5596&dec=24.22634&zoom=14">UGC5094</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5129.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5129.png" alt="UGC5129" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5299.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5299.png" alt="UGC5299" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5377.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5377.png" alt="UGC5377" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5638.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5638.png" alt="UGC5638" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5713.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5713.png" alt="UGC5713" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=144.4916&dec=25.49481&zoom=14">UGC5129</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=148.1720&dec=-0.18406&zoom=14">UGC5299</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=150.1315&dec=3.20531&zoom=14">UGC5377</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=156.3363&dec=26.45964&zoom=14">UGC5638</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=157.9120&dec=25.98397&zoom=14">UGC5713</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC5830.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC5830.png" alt="UGC5830" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC6252.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC6252.png" alt="UGC6252" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC6697.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC6697.png" alt="UGC6697" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC6881.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC6881.png" alt="UGC6881" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7049.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7049.png" alt="UGC7049" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=160.6587&dec=23.95178&zoom=14">UGC5830</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=168.3293&dec=25.86264&zoom=14">UGC6252</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=175.9546&dec=19.96839&zoom=14">UGC6697</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=178.6863&dec=20.05556&zoom=14">UGC6881</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=181.0398&dec=20.18469&zoom=14">UGC7049</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7133.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7133.png" alt="UGC7133" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7148.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7148.png" alt="UGC7148" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7237.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7237.png" alt="UGC7237" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7263.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7263.png" alt="UGC7263" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7280.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7280.png" alt="UGC7280" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=182.3324&dec=18.99742&zoom=14">UGC7133</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=182.4745&dec=0.92856&zoom=14">UGC7148</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=183.5053&dec=17.90011&zoom=14">UGC7237</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=183.8549&dec=19.29239&zoom=14">UGC7263</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=183.9688&dec=0.40075&zoom=14">UGC7280</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7331.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7331.png" alt="UGC7331" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7370.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7370.png" alt="UGC7370" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7396.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7396.png" alt="UGC7396" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC7697.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC7697.png" alt="UGC7697" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC8067.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC8067.png" alt="UGC8067" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=184.4730&dec=17.44214&zoom=14">UGC7331</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=184.9180&dec=2.08047&zoom=14">UGC7370</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=185.1407&dec=0.78822&zoom=14">UGC7396</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=188.2151&dec=20.18367&zoom=14">UGC7697</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=194.3005&dec=-1.70711&zoom=14">UGC8067</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC8238.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC8238.png" alt="UGC8238" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC8448.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC8448.png" alt="UGC8448" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC8473.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC8473.png" alt="UGC8473" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9002.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9002.png" alt="UGC9002" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9044.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9044.png" alt="UGC9044" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=197.4212&dec=-1.04828&zoom=14">UGC8238</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=201.6663&dec=19.94456&zoom=14">UGC8448</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=202.3551&dec=-0.39906&zoom=14">UGC8473</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=211.2235&dec=12.72153&zoom=14">UGC9002</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=212.2596&dec=14.31694&zoom=14">UGC9044</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9221-UGC9222.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9221-UGC9222.png" alt="UGC9221-UGC9222" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9224.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9224.png" alt="UGC9224" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9243.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9243.png" alt="UGC9243" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9273.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9273.png" alt="UGC9273" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9279.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9279.png" alt="UGC9279" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=215.9348&dec=34.01301&zoom=14">UGC9221-UGC9222</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=215.9770&dec=34.72353&zoom=14">UGC9224</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=216.3885&dec=33.84811&zoom=14">UGC9243</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=217.0453&dec=13.55158&zoom=14">UGC9273</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=217.0248&dec=33.81828&zoom=14">UGC9279</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9288.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9288.png" alt="UGC9288" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9367.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9367.png" alt="UGC9367" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9491.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9491.png" alt="UGC9491" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9659.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9659.png" alt="UGC9659" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9667.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9667.png" alt="UGC9667" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=217.2426&dec=13.86181&zoom=14">UGC9288</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=218.3270&dec=34.73456&zoom=14">UGC9367</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=221.0614&dec=4.21848&zoom=14">UGC9491</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=225.4548&dec=4.93225&zoom=14">UGC9659</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=225.5820&dec=5.64669&zoom=14">UGC9667</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9694.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9694.png" alt="UGC9694" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9732.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9732.png" alt="UGC9732" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9744.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9744.png" alt="UGC9744" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9746.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9746.png" alt="UGC9746" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9751.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9751.png" alt="UGC9751" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=226.3342&dec=4.48056&zoom=14">UGC9694</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.0408&dec=1.24934&zoom=14">UGC9732</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.4639&dec=1.77882&zoom=14">UGC9744</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.5690&dec=1.93427&zoom=14">UGC9746</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.7438&dec=1.43750&zoom=14">UGC9751</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9757.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9757.png" alt="UGC9757" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9758.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9758.png" alt="UGC9758" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9781.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9781.png" alt="UGC9781" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9785.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9785.png" alt="UGC9785" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9787.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9787.png" alt="UGC9787" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.9057&dec=5.39753&zoom=14">UGC9757</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=227.8668&dec=13.48351&zoom=14">UGC9758</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.7064&dec=5.54765&zoom=14">UGC9781</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.8093&dec=5.18986&zoom=14">UGC9785</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=228.9287&dec=1.45551&zoom=14">UGC9787</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9808.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9808.png" alt="UGC9808" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9889.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9889.png" alt="UGC9889" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9901.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9901.png" alt="UGC9901" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9919.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9919.png" alt="UGC9919" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9941.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9941.png" alt="UGC9941" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=229.5358&dec=13.82867&zoom=14">UGC9808</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=233.2698&dec=0.55631&zoom=14">UGC9889</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=233.6122&dec=12.27100&zoom=14">UGC9901</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=233.9150&dec=12.60642&zoom=14">UGC9919</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=234.5921&dec=12.96083&zoom=14">UGC9941</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9945.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9945.png" alt="UGC9945" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9951.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9951.png" alt="UGC9951" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9953.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9953.png" alt="UGC9953" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9960.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9960.png" alt="UGC9960" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9962.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9962.png" alt="UGC9962" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=234.7287&dec=4.58306&zoom=14">UGC9945</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=234.8338&dec=15.38389&zoom=14">UGC9951</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=234.9144&dec=3.19903&zoom=14">UGC9953</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.0239&dec=1.93369&zoom=14">UGC9960</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.0142&dec=13.97750&zoom=14">UGC9962</a>
</td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9968.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9968.png" alt="UGC9968" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9976.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9976.png" alt="UGC9976" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9980.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9980.png" alt="UGC9980" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9990.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9990.png" alt="UGC9990" /></a></td>
<td style="width:20%;word-wrap:break-word;"><a href="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/UGC9991.png"><img src="https://portal.nersc.gov/project/cosmo/data/legacysurvey/dr2/gallery/png/thumb-UGC9991.png" alt="UGC9991" /></a></td>
</tr>
<tr>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.2911&dec=-1.70619&zoom=14">UGC9968</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.4598&dec=5.85379&zoom=14">UGC9976</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.6429&dec=2.01428&zoom=14">UGC9980</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.8745&dec=4.79444&zoom=14">UGC9990</a>
</td>
<td style="width:20%;word-wrap:break-word;" class="left"><a href="https://www.legacysurvey.org/viewer/?layer=ls-dr9&ra=235.8468&dec=14.43569&zoom=14">UGC9991</a>
</td>
</tr>
</tbody>
</table>
